Updated navbar functionalities
cia-ulaval/LENIA-frontend pull request #9
Opened 2024-04-06 20:50 UTC by Louis-Etienne

Ajout des fonctionnalités du navbar!

(C'est pas encore fini, mais je voulais juste un avis général de ce que j'ai fais :)) )

2024-04-06 20:59 UTC, Louis-Etienne commented
Image  du menu principal
![image](https://github.com/cia-ulaval/LENIA-frontend/assets/151950203/7b58fe91-48ef-4ece-bc0d-67cfe72009d7)

Image de la page How to Use
![image](https://github.com/cia-ulaval/LENIA-frontend/assets/151950203/c069088a-d1e7-425b-934f-036ba4fd7281)

2024-04-06 23:31 UTC, John-WL commented on src/components/SecondaryPages/aboutUs.tsx
Dans ce fichier, `ContactUs.tsx` et `hotToUse.tsx`, on a beaucoup de duplication de sytles. Ça pourrait être nice de les regrouper certains attributs ensembles dans un fichier à part si le but est qu'ils soient tous les mêmes.

2024-04-06 23:33 UTC, John-WL requested changes
Je ne vois pas de problème à part pour la duplication des styles qu'il faudrait gérer.

2024-04-07 15:36 UTC, Louis-Etienne commented on src/components/SecondaryPages/aboutUs.tsx
Parfait! Je suis d'accord, je me disais justement que c'était pas clean. Je vais probablement faire un fichier .tsx avec juste des styles globaux

2024-04-07 15:43 UTC, John-WL commented on src/components/SecondaryPages/aboutUs.tsx
Je recommende de le faire juste pour ceux qui sont dupliqués. Les autres peuvent rester dans leur fichiers components qui leur correspondent.

2024-04-07 15:43 UTC, John-WL commented on src/components/SecondaryPages/aboutUs.tsx
Par exemple, le style du right panel à pas besoin d'être séparé pour le moment.

2024-04-07 15:54 UTC, John-WL commented on src/components/SecondaryPages/aboutUs.tsx
N'hésites pas à le dire si tu trouve encore que "[c'est] pas clean". Je propose des changements, mais au final c'est mon premier projet en react + typescript. C'est une bonne idée de discuter des pours et des contres.

2024-04-07 20:41 UTC, Louis-Etienne commented
J'ai règler la duplication des styles et j'ai terminé les pages Contact Us et Abous us!
Ça serait prêt à merge si j'ai ton accord :))

2024-04-07 21:57 UTC, John-WL approved these changes

2024-04-07 21:58 UTC, merged